# Generated by Django 2.0.6 on 2018-06-10 08:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='账号')),
                ('password', models.CharField(db_index=True, max_length=64, verbose_name='密码')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='邮箱')),
                ('nickname', models.CharField(max_length=64, null=True, verbose_name='昵称')),
                ('head_img', models.ImageField(blank=True, null=True, upload_to='upload/7ffd33db-8f65-43ce-a193-ca3e6dad6fb5/', verbose_name='头像')),
                ('telephone', models.CharField(blank=True, max_length=11, null=True, verbose_name='电话')),
                ('sex', models.CharField(max_length=2, null=True, verbose_name='性别')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('is_superuser', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
