# Generated by Django 2.0.6 on 2018-06-10 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='head_img',
            field=models.ImageField(blank=True, null=True, upload_to='upload/8c1d47f0-25f1-4113-8a4e-4029d5ebdaf1/', verbose_name='头像'),
        ),
    ]
